language: python
python:
  - 3.5
install:
  - pip install -r requirements.txt
before_script:
  - python create_droplets.py
  - eval "$(ssh-agent -s)"
  - echo ${SSH_KEY} | base64 -d > /tmp/id_rsa
  - chmod 600 /tmp/id_rsa
  - ssh-add /tmp/id_rsa
script:
  - cat inventory
  - ansible-playbook -e 'host_key_checking=False' create_file.yaml -i inventory
after_script:
  - # python delete_droplets.py
