language: python
python:
  - 3.5
install:
  - pip install -r requirements.txt
before_install:
  - echo ${SSH_KEY} | base64 -d > /tmp/id_rsa
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_rsa
  - ssh-add /tmp/id_rsa
script:
  - python test.py